spring:
    application:
        name: demo


server:
    tomcat:
        max-threads: 10
        accept-count: 10

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-test-one.sk.9f.cn/eureka/
